# Generated by Django 5.1.4 on 2024-12-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libros',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=10)),
                ('titulo', models.CharField(max_length=100)),
                ('libro', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('codigof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_libros.libros')),
                ('cedulaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_libros.usuario')),
            ],
        ),
    ]
